language: node_js
sudo: false

os:
  - linux

node_js:
  - '14'
  - '12'
  - '10'

before_install:
  - npm i -g npm@6.14.11

install:
  - travis_retry npm install
  - travis_retry npm run bootstrap

stages:
  - test
  - performance

jobs:
  include:

    - stage: test
      script:
        - npm test

    - stage: performance
      name: "webpack-dev-server typescript"
      env:
        - transpiler="typescript"
      sudo: false
      node_js:
        - '14'
      install:
        - travis_retry npm install
        - travis_retry npm run bootstrap
        - cd performance
        - travis_retry npm install
      script:
        - node measure-dev-server.js

    - stage: performance
      name: "webpack-dev-server babel"
      env:
        - transpiler="babel"
      sudo: false
      node_js:
        - '14'
      install:
        - travis_retry npm install
        - travis_retry npm run bootstrap
        - cd performance
        - travis_retry npm install
      script:
        - node measure-dev-server.js

    - stage: performance
      name: "webpack-dev-server typescript - components x 10"
      env:
        - transpiler="typescript"
        - moduleMultiplier="10"
      sudo: false
      node_js:
        - '14'
      install:
        - travis_retry npm install
        - travis_retry npm run bootstrap
        - cd performance
        - travis_retry npm install
      script:
        - node measure-dev-server.js

    - stage: performance
      name: "webpack-dev-server babel - components x 10"
      env:
        - transpiler="babel"
        - moduleMultiplier="10"
      sudo: false
      node_js:
        - '14'
      install:
        - travis_retry npm install
        - travis_retry npm run bootstrap
        - cd performance
        - travis_retry npm install
      script:
        - node measure-dev-server.js

    - stage: performance
      name: "webpack-cli typescript"
      env:
        - transpiler="typescript"
      sudo: false
      node_js:
        - '14'
      install:
        - travis_retry npm install
        - travis_retry npm run bootstrap
        - cd performance
        - travis_retry npm install
      script:
        - node measure-cli-build.js

    - stage: performance
      name: "webpack-cli babel"
      env:
        - transpiler="babel"
      sudo: false
      node_js:
        - '14'
      install:
        - travis_retry npm install
        - travis_retry npm run bootstrap
        - cd performance
        - travis_retry npm install
      script:
        - node measure-cli-build.js
